//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TW.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TW.Common.Properties.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找類似 
        ///{
        ///    &quot;Aatrox&quot;: &quot;\u51a5\u8840\u90aa\u528d-\u5384\u85a9\u65af&quot;,
        ///    &quot;Ahri&quot;: &quot;\u4e5d\u5c3e\u5996\u72d0-\u963f\u7483&quot;,
        ///    &quot;Akali&quot;: &quot;\u6697\u5f71\u4e4b\u62f3-\u963f\u5361\u8389&quot;,
        ///    &quot;Alistar&quot;: &quot;\u725b\u982d\u914b\u9577-\u4e9e\u6b77\u65af\u5854&quot;,
        ///    &quot;Amumu&quot;: &quot;\u6ba4\u4e4b\u6728\u4e43\u4f0a-\u963f\u59c6\u59c6&quot;,
        ///    &quot;Anivia&quot;: &quot;\u51b0\u6676\u9cf3\u51f0-\u827e\u59ae\u7dad\u4e9e&quot;,
        ///    &quot;Annie&quot;: &quot;\u9ed1\u6697\u4e4b\u5973-\u5b89\u59ae&quot;,
        ///    &quot;Ashe&quot;: &quot;\u51b0\u971c\u5c04\u624b-\u827e\u5e0c&quot;,
        ///    &quot;Azir&quot;: &quot;\u86 [字符串的其餘部分被截斷]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TraditionalChineseJson {
            get {
                return ResourceManager.GetString("TraditionalChineseJson", resourceCulture);
            }
        }
    }
}